[template]
cargo_generate_version = ">=0.23.3"
include = ["**/*.jinja", "src/lib.rs"]
ignore = [".generate/test-generate.toml", "cargo-generate-test.sh"]

[conditional.'crate_type == "lib"']
ignore = ["src/main.rs"]

[conditional.'crate_type == "bin"']
ignore = ["src/lib.rs"]

[conditional.'!wasm']
ignore = ["index.html", "src/tests", "src/lib.wasm.rs"]

[hooks]
post = [".generate/post-script.rhai"]

[placeholders]
description = { type = "string", prompt = "Description for the crate?", default = "" }
publishable = { type = "bool", prompt = "Will this crate be published?", default = true }
strict_lints = { type = "bool", prompt = "Enable strict lints?", default = true }
test = { type = "bool", prompt = "Test the result of the generation?", default = false }
wasm = { type = "bool", prompt = "Generate a WASM-capable crate?", default = false }
